# Generated by Django 2.2.4 on 2019-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
